/*
 * generated by Xtext 2.32.0
 */
package fr.enseeiht.xtext.tocl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class ToclProposalProvider extends AbstractToclProposalProvider {
}
