/**
 * generated by Xtext 2.32.0
 */
package fr.enseeiht.xtext.tocl.tocl.util;

import fr.enseeiht.xtext.tocl.tocl.AddOpCallExp;
import fr.enseeiht.xtext.tocl.tocl.Attribute;
import fr.enseeiht.xtext.tocl.tocl.Auxiliary;
import fr.enseeiht.xtext.tocl.tocl.BagExp;
import fr.enseeiht.xtext.tocl.tocl.BagType;
import fr.enseeiht.xtext.tocl.tocl.BoolOpCallExp;
import fr.enseeiht.xtext.tocl.tocl.BooleanExp;
import fr.enseeiht.xtext.tocl.tocl.BooleanType;
import fr.enseeiht.xtext.tocl.tocl.BraceExp;
import fr.enseeiht.xtext.tocl.tocl.CollectionOperationCall;
import fr.enseeiht.xtext.tocl.tocl.CollectionType;
import fr.enseeiht.xtext.tocl.tocl.EnumLiteralExp;
import fr.enseeiht.xtext.tocl.tocl.EqOpCallExp;
import fr.enseeiht.xtext.tocl.tocl.IfExp;
import fr.enseeiht.xtext.tocl.tocl.Import;
import fr.enseeiht.xtext.tocl.tocl.IntOpCallExp;
import fr.enseeiht.xtext.tocl.tocl.IntegerExp;
import fr.enseeiht.xtext.tocl.tocl.IntegerType;
import fr.enseeiht.xtext.tocl.tocl.IterateExp;
import fr.enseeiht.xtext.tocl.tocl.Iterator;
import fr.enseeiht.xtext.tocl.tocl.IteratorExp;
import fr.enseeiht.xtext.tocl.tocl.LetExp;
import fr.enseeiht.xtext.tocl.tocl.LocalVariable;
import fr.enseeiht.xtext.tocl.tocl.MapElement;
import fr.enseeiht.xtext.tocl.tocl.MapExp;
import fr.enseeiht.xtext.tocl.tocl.MapType;
import fr.enseeiht.xtext.tocl.tocl.ModuleElement;
import fr.enseeiht.xtext.tocl.tocl.MulOpCallExp;
import fr.enseeiht.xtext.tocl.tocl.NavigationOrAttributeCall;
import fr.enseeiht.xtext.tocl.tocl.NumericExp;
import fr.enseeiht.xtext.tocl.tocl.NumericType;
import fr.enseeiht.xtext.tocl.tocl.OclAnyType;
import fr.enseeiht.xtext.tocl.tocl.OclExpression;
import fr.enseeiht.xtext.tocl.tocl.OclFeatureDefinition;
import fr.enseeiht.xtext.tocl.tocl.OclInvariant;
import fr.enseeiht.xtext.tocl.tocl.OclModelElement;
import fr.enseeiht.xtext.tocl.tocl.OclModelElementExp;
import fr.enseeiht.xtext.tocl.tocl.OclModuleElement;
import fr.enseeiht.xtext.tocl.tocl.OclType;
import fr.enseeiht.xtext.tocl.tocl.OclUndefinedExp;
import fr.enseeiht.xtext.tocl.tocl.Operation;
import fr.enseeiht.xtext.tocl.tocl.OperationCall;
import fr.enseeiht.xtext.tocl.tocl.OperatorCallExp;
import fr.enseeiht.xtext.tocl.tocl.OrderedSetExp;
import fr.enseeiht.xtext.tocl.tocl.OrderedSetType;
import fr.enseeiht.xtext.tocl.tocl.Parameter;
import fr.enseeiht.xtext.tocl.tocl.Primitive;
import fr.enseeiht.xtext.tocl.tocl.PropertyCall;
import fr.enseeiht.xtext.tocl.tocl.PropertyCallExp;
import fr.enseeiht.xtext.tocl.tocl.RealExp;
import fr.enseeiht.xtext.tocl.tocl.RealType;
import fr.enseeiht.xtext.tocl.tocl.RelOpCallExp;
import fr.enseeiht.xtext.tocl.tocl.SelfExp;
import fr.enseeiht.xtext.tocl.tocl.SequenceExp;
import fr.enseeiht.xtext.tocl.tocl.SequenceType;
import fr.enseeiht.xtext.tocl.tocl.SetExp;
import fr.enseeiht.xtext.tocl.tocl.SetType;
import fr.enseeiht.xtext.tocl.tocl.StringExp;
import fr.enseeiht.xtext.tocl.tocl.StringType;
import fr.enseeiht.xtext.tocl.tocl.SuperExp;
import fr.enseeiht.xtext.tocl.tocl.ToclPackage;
import fr.enseeiht.xtext.tocl.tocl.TupleExp;
import fr.enseeiht.xtext.tocl.tocl.TuplePart;
import fr.enseeiht.xtext.tocl.tocl.TupleType;
import fr.enseeiht.xtext.tocl.tocl.TupleTypeAttribute;
import fr.enseeiht.xtext.tocl.tocl.VariableDeclaration;
import fr.enseeiht.xtext.tocl.tocl.VariableExp;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see fr.enseeiht.xtext.tocl.tocl.ToclPackage
 * @generated
 */
public class ToclAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static ToclPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ToclAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = ToclPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ToclSwitch<Adapter> modelSwitch =
    new ToclSwitch<Adapter>()
    {
      @Override
      public Adapter caseModule(fr.enseeiht.xtext.tocl.tocl.Module object)
      {
        return createModuleAdapter();
      }
      @Override
      public Adapter caseImport(Import object)
      {
        return createImportAdapter();
      }
      @Override
      public Adapter caseModuleElement(ModuleElement object)
      {
        return createModuleElementAdapter();
      }
      @Override
      public Adapter caseOclModuleElement(OclModuleElement object)
      {
        return createOclModuleElementAdapter();
      }
      @Override
      public Adapter caseOclFeatureDefinition(OclFeatureDefinition object)
      {
        return createOclFeatureDefinitionAdapter();
      }
      @Override
      public Adapter caseAttribute(Attribute object)
      {
        return createAttributeAdapter();
      }
      @Override
      public Adapter caseOperation(Operation object)
      {
        return createOperationAdapter();
      }
      @Override
      public Adapter caseParameter(Parameter object)
      {
        return createParameterAdapter();
      }
      @Override
      public Adapter caseOclInvariant(OclInvariant object)
      {
        return createOclInvariantAdapter();
      }
      @Override
      public Adapter caseOclExpression(OclExpression object)
      {
        return createOclExpressionAdapter();
      }
      @Override
      public Adapter caseOclModelElementExp(OclModelElementExp object)
      {
        return createOclModelElementExpAdapter();
      }
      @Override
      public Adapter caseOperatorCallExp(OperatorCallExp object)
      {
        return createOperatorCallExpAdapter();
      }
      @Override
      public Adapter casePropertyCallExp(PropertyCallExp object)
      {
        return createPropertyCallExpAdapter();
      }
      @Override
      public Adapter caseAuxiliary(Auxiliary object)
      {
        return createAuxiliaryAdapter();
      }
      @Override
      public Adapter caseVariableExp(VariableExp object)
      {
        return createVariableExpAdapter();
      }
      @Override
      public Adapter caseVariableDeclaration(VariableDeclaration object)
      {
        return createVariableDeclarationAdapter();
      }
      @Override
      public Adapter caseSuperExp(SuperExp object)
      {
        return createSuperExpAdapter();
      }
      @Override
      public Adapter caseSelfExp(SelfExp object)
      {
        return createSelfExpAdapter();
      }
      @Override
      public Adapter caseStringExp(StringExp object)
      {
        return createStringExpAdapter();
      }
      @Override
      public Adapter caseNumericExp(NumericExp object)
      {
        return createNumericExpAdapter();
      }
      @Override
      public Adapter caseRealExp(RealExp object)
      {
        return createRealExpAdapter();
      }
      @Override
      public Adapter caseIntegerExp(IntegerExp object)
      {
        return createIntegerExpAdapter();
      }
      @Override
      public Adapter caseBagExp(BagExp object)
      {
        return createBagExpAdapter();
      }
      @Override
      public Adapter caseOrderedSetExp(OrderedSetExp object)
      {
        return createOrderedSetExpAdapter();
      }
      @Override
      public Adapter caseSequenceExp(SequenceExp object)
      {
        return createSequenceExpAdapter();
      }
      @Override
      public Adapter caseSetExp(SetExp object)
      {
        return createSetExpAdapter();
      }
      @Override
      public Adapter caseTupleExp(TupleExp object)
      {
        return createTupleExpAdapter();
      }
      @Override
      public Adapter caseTuplePart(TuplePart object)
      {
        return createTuplePartAdapter();
      }
      @Override
      public Adapter caseMapExp(MapExp object)
      {
        return createMapExpAdapter();
      }
      @Override
      public Adapter caseMapElement(MapElement object)
      {
        return createMapElementAdapter();
      }
      @Override
      public Adapter caseEnumLiteralExp(EnumLiteralExp object)
      {
        return createEnumLiteralExpAdapter();
      }
      @Override
      public Adapter caseOclUndefinedExp(OclUndefinedExp object)
      {
        return createOclUndefinedExpAdapter();
      }
      @Override
      public Adapter caseLetExp(LetExp object)
      {
        return createLetExpAdapter();
      }
      @Override
      public Adapter caseIfExp(IfExp object)
      {
        return createIfExpAdapter();
      }
      @Override
      public Adapter caseBraceExp(BraceExp object)
      {
        return createBraceExpAdapter();
      }
      @Override
      public Adapter caseBooleanExp(BooleanExp object)
      {
        return createBooleanExpAdapter();
      }
      @Override
      public Adapter casePropertyCall(PropertyCall object)
      {
        return createPropertyCallAdapter();
      }
      @Override
      public Adapter caseOperationCall(OperationCall object)
      {
        return createOperationCallAdapter();
      }
      @Override
      public Adapter caseNavigationOrAttributeCall(NavigationOrAttributeCall object)
      {
        return createNavigationOrAttributeCallAdapter();
      }
      @Override
      public Adapter caseIterateExp(IterateExp object)
      {
        return createIterateExpAdapter();
      }
      @Override
      public Adapter caseIterator(Iterator object)
      {
        return createIteratorAdapter();
      }
      @Override
      public Adapter caseIteratorExp(IteratorExp object)
      {
        return createIteratorExpAdapter();
      }
      @Override
      public Adapter caseCollectionOperationCall(CollectionOperationCall object)
      {
        return createCollectionOperationCallAdapter();
      }
      @Override
      public Adapter caseLocalVariable(LocalVariable object)
      {
        return createLocalVariableAdapter();
      }
      @Override
      public Adapter caseOclType(OclType object)
      {
        return createOclTypeAdapter();
      }
      @Override
      public Adapter caseCollectionType(CollectionType object)
      {
        return createCollectionTypeAdapter();
      }
      @Override
      public Adapter caseBagType(BagType object)
      {
        return createBagTypeAdapter();
      }
      @Override
      public Adapter caseOrderedSetType(OrderedSetType object)
      {
        return createOrderedSetTypeAdapter();
      }
      @Override
      public Adapter caseSequenceType(SequenceType object)
      {
        return createSequenceTypeAdapter();
      }
      @Override
      public Adapter caseSetType(SetType object)
      {
        return createSetTypeAdapter();
      }
      @Override
      public Adapter casePrimitive(Primitive object)
      {
        return createPrimitiveAdapter();
      }
      @Override
      public Adapter caseStringType(StringType object)
      {
        return createStringTypeAdapter();
      }
      @Override
      public Adapter caseBooleanType(BooleanType object)
      {
        return createBooleanTypeAdapter();
      }
      @Override
      public Adapter caseNumericType(NumericType object)
      {
        return createNumericTypeAdapter();
      }
      @Override
      public Adapter caseIntegerType(IntegerType object)
      {
        return createIntegerTypeAdapter();
      }
      @Override
      public Adapter caseRealType(RealType object)
      {
        return createRealTypeAdapter();
      }
      @Override
      public Adapter caseOclAnyType(OclAnyType object)
      {
        return createOclAnyTypeAdapter();
      }
      @Override
      public Adapter caseTupleType(TupleType object)
      {
        return createTupleTypeAdapter();
      }
      @Override
      public Adapter caseTupleTypeAttribute(TupleTypeAttribute object)
      {
        return createTupleTypeAttributeAdapter();
      }
      @Override
      public Adapter caseOclModelElement(OclModelElement object)
      {
        return createOclModelElementAdapter();
      }
      @Override
      public Adapter caseMapType(MapType object)
      {
        return createMapTypeAdapter();
      }
      @Override
      public Adapter caseBoolOpCallExp(BoolOpCallExp object)
      {
        return createBoolOpCallExpAdapter();
      }
      @Override
      public Adapter caseEqOpCallExp(EqOpCallExp object)
      {
        return createEqOpCallExpAdapter();
      }
      @Override
      public Adapter caseRelOpCallExp(RelOpCallExp object)
      {
        return createRelOpCallExpAdapter();
      }
      @Override
      public Adapter caseAddOpCallExp(AddOpCallExp object)
      {
        return createAddOpCallExpAdapter();
      }
      @Override
      public Adapter caseIntOpCallExp(IntOpCallExp object)
      {
        return createIntOpCallExpAdapter();
      }
      @Override
      public Adapter caseMulOpCallExp(MulOpCallExp object)
      {
        return createMulOpCallExpAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.Module <em>Module</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.Module
   * @generated
   */
  public Adapter createModuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.Import
   * @generated
   */
  public Adapter createImportAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.ModuleElement <em>Module Element</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.ModuleElement
   * @generated
   */
  public Adapter createModuleElementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.OclModuleElement <em>Ocl Module Element</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.OclModuleElement
   * @generated
   */
  public Adapter createOclModuleElementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.OclFeatureDefinition <em>Ocl Feature Definition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.OclFeatureDefinition
   * @generated
   */
  public Adapter createOclFeatureDefinitionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.Attribute
   * @generated
   */
  public Adapter createAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.Operation
   * @generated
   */
  public Adapter createOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.Parameter
   * @generated
   */
  public Adapter createParameterAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.OclInvariant <em>Ocl Invariant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.OclInvariant
   * @generated
   */
  public Adapter createOclInvariantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.OclExpression <em>Ocl Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.OclExpression
   * @generated
   */
  public Adapter createOclExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.OclModelElementExp <em>Ocl Model Element Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.OclModelElementExp
   * @generated
   */
  public Adapter createOclModelElementExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.OperatorCallExp <em>Operator Call Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.OperatorCallExp
   * @generated
   */
  public Adapter createOperatorCallExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.PropertyCallExp <em>Property Call Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.PropertyCallExp
   * @generated
   */
  public Adapter createPropertyCallExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.Auxiliary <em>Auxiliary</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.Auxiliary
   * @generated
   */
  public Adapter createAuxiliaryAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.VariableExp <em>Variable Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.VariableExp
   * @generated
   */
  public Adapter createVariableExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.VariableDeclaration
   * @generated
   */
  public Adapter createVariableDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.SuperExp <em>Super Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.SuperExp
   * @generated
   */
  public Adapter createSuperExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.SelfExp <em>Self Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.SelfExp
   * @generated
   */
  public Adapter createSelfExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.StringExp <em>String Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.StringExp
   * @generated
   */
  public Adapter createStringExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.NumericExp <em>Numeric Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.NumericExp
   * @generated
   */
  public Adapter createNumericExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.RealExp <em>Real Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.RealExp
   * @generated
   */
  public Adapter createRealExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.IntegerExp <em>Integer Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.IntegerExp
   * @generated
   */
  public Adapter createIntegerExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.BagExp <em>Bag Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.BagExp
   * @generated
   */
  public Adapter createBagExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.OrderedSetExp <em>Ordered Set Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.OrderedSetExp
   * @generated
   */
  public Adapter createOrderedSetExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.SequenceExp <em>Sequence Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.SequenceExp
   * @generated
   */
  public Adapter createSequenceExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.SetExp <em>Set Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.SetExp
   * @generated
   */
  public Adapter createSetExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.TupleExp <em>Tuple Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.TupleExp
   * @generated
   */
  public Adapter createTupleExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.TuplePart <em>Tuple Part</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.TuplePart
   * @generated
   */
  public Adapter createTuplePartAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.MapExp <em>Map Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.MapExp
   * @generated
   */
  public Adapter createMapExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.MapElement <em>Map Element</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.MapElement
   * @generated
   */
  public Adapter createMapElementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.EnumLiteralExp <em>Enum Literal Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.EnumLiteralExp
   * @generated
   */
  public Adapter createEnumLiteralExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.OclUndefinedExp <em>Ocl Undefined Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.OclUndefinedExp
   * @generated
   */
  public Adapter createOclUndefinedExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.LetExp <em>Let Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.LetExp
   * @generated
   */
  public Adapter createLetExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.IfExp <em>If Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.IfExp
   * @generated
   */
  public Adapter createIfExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.BraceExp <em>Brace Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.BraceExp
   * @generated
   */
  public Adapter createBraceExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.BooleanExp <em>Boolean Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.BooleanExp
   * @generated
   */
  public Adapter createBooleanExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.PropertyCall <em>Property Call</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.PropertyCall
   * @generated
   */
  public Adapter createPropertyCallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.OperationCall <em>Operation Call</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.OperationCall
   * @generated
   */
  public Adapter createOperationCallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.NavigationOrAttributeCall <em>Navigation Or Attribute Call</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.NavigationOrAttributeCall
   * @generated
   */
  public Adapter createNavigationOrAttributeCallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.IterateExp <em>Iterate Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.IterateExp
   * @generated
   */
  public Adapter createIterateExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.Iterator <em>Iterator</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.Iterator
   * @generated
   */
  public Adapter createIteratorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.IteratorExp <em>Iterator Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.IteratorExp
   * @generated
   */
  public Adapter createIteratorExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.CollectionOperationCall <em>Collection Operation Call</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.CollectionOperationCall
   * @generated
   */
  public Adapter createCollectionOperationCallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.LocalVariable <em>Local Variable</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.LocalVariable
   * @generated
   */
  public Adapter createLocalVariableAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.OclType <em>Ocl Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.OclType
   * @generated
   */
  public Adapter createOclTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.CollectionType <em>Collection Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.CollectionType
   * @generated
   */
  public Adapter createCollectionTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.BagType <em>Bag Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.BagType
   * @generated
   */
  public Adapter createBagTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.OrderedSetType <em>Ordered Set Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.OrderedSetType
   * @generated
   */
  public Adapter createOrderedSetTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.SequenceType <em>Sequence Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.SequenceType
   * @generated
   */
  public Adapter createSequenceTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.SetType <em>Set Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.SetType
   * @generated
   */
  public Adapter createSetTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.Primitive <em>Primitive</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.Primitive
   * @generated
   */
  public Adapter createPrimitiveAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.StringType <em>String Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.StringType
   * @generated
   */
  public Adapter createStringTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.BooleanType <em>Boolean Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.BooleanType
   * @generated
   */
  public Adapter createBooleanTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.NumericType <em>Numeric Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.NumericType
   * @generated
   */
  public Adapter createNumericTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.IntegerType <em>Integer Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.IntegerType
   * @generated
   */
  public Adapter createIntegerTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.RealType <em>Real Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.RealType
   * @generated
   */
  public Adapter createRealTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.OclAnyType <em>Ocl Any Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.OclAnyType
   * @generated
   */
  public Adapter createOclAnyTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.TupleType <em>Tuple Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.TupleType
   * @generated
   */
  public Adapter createTupleTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.TupleTypeAttribute <em>Tuple Type Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.TupleTypeAttribute
   * @generated
   */
  public Adapter createTupleTypeAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.OclModelElement <em>Ocl Model Element</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.OclModelElement
   * @generated
   */
  public Adapter createOclModelElementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.MapType <em>Map Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.MapType
   * @generated
   */
  public Adapter createMapTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.BoolOpCallExp <em>Bool Op Call Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.BoolOpCallExp
   * @generated
   */
  public Adapter createBoolOpCallExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.EqOpCallExp <em>Eq Op Call Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.EqOpCallExp
   * @generated
   */
  public Adapter createEqOpCallExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.RelOpCallExp <em>Rel Op Call Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.RelOpCallExp
   * @generated
   */
  public Adapter createRelOpCallExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.AddOpCallExp <em>Add Op Call Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.AddOpCallExp
   * @generated
   */
  public Adapter createAddOpCallExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.IntOpCallExp <em>Int Op Call Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.IntOpCallExp
   * @generated
   */
  public Adapter createIntOpCallExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.enseeiht.xtext.tocl.tocl.MulOpCallExp <em>Mul Op Call Exp</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.enseeiht.xtext.tocl.tocl.MulOpCallExp
   * @generated
   */
  public Adapter createMulOpCallExpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //ToclAdapterFactory
