/**
 * generated by Xtext 2.37.0
 */
package fr.enseeiht.ocl.xtext.ocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Op Call Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getAddOpCallExp()
 * @model
 * @generated
 */
public interface AddOpCallExp extends OperatorCallExp
{
} // AddOpCallExp
