/**
 * generated by Xtext 2.37.0
 */
package fr.enseeiht.ocl.xtext.ocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bag Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getBagType()
 * @model
 * @generated
 */
public interface BagType extends CollectionType
{
} // BagType
