/**
 * generated by Xtext
 */
package fr.enseeiht.ocl.xtext.ocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.ocl.xtext.ocl.BooleanExp#getBooleanSymbol <em>Boolean Symbol</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getBooleanExp()
 * @model
 * @generated
 */
public interface BooleanExp extends OclExpression
{
  /**
   * Returns the value of the '<em><b>Boolean Symbol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Boolean Symbol</em>' attribute.
   * @see #setBooleanSymbol(String)
   * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getBooleanExp_BooleanSymbol()
   * @model
   * @generated
   */
  String getBooleanSymbol();

  /**
   * Sets the value of the '{@link fr.enseeiht.ocl.xtext.ocl.BooleanExp#getBooleanSymbol <em>Boolean Symbol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Boolean Symbol</em>' attribute.
   * @see #getBooleanSymbol()
   * @generated
   */
  void setBooleanSymbol(String value);

} // BooleanExp
