/**
 * generated by Xtext
 */
package fr.enseeiht.ocl.xtext.ocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Let Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.ocl.xtext.ocl.LetExp#getVariable <em>Variable</em>}</li>
 *   <li>{@link fr.enseeiht.ocl.xtext.ocl.LetExp#getIn_ <em>In </em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getLetExp()
 * @model
 * @generated
 */
public interface LetExp extends OclExpression
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(LocalVariable)
   * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getLetExp_Variable()
   * @model containment="true"
   * @generated
   */
  LocalVariable getVariable();

  /**
   * Sets the value of the '{@link fr.enseeiht.ocl.xtext.ocl.LetExp#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(LocalVariable value);

  /**
   * Returns the value of the '<em><b>In </b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>In </em>' containment reference.
   * @see #setIn_(OclExpression)
   * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getLetExp_In_()
   * @model containment="true"
   * @generated
   */
  OclExpression getIn_();

  /**
   * Sets the value of the '{@link fr.enseeiht.ocl.xtext.ocl.LetExp#getIn_ <em>In </em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>In </em>' containment reference.
   * @see #getIn_()
   * @generated
   */
  void setIn_(OclExpression value);

} // LetExp
