/**
 * generated by Xtext
 */
package fr.enseeiht.ocl.xtext.ocl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Not Op Call Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.ocl.xtext.ocl.NotOpCallExp#getOperationName <em>Operation Name</em>}</li>
 *   <li>{@link fr.enseeiht.ocl.xtext.ocl.NotOpCallExp#getSource <em>Source</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getNotOpCallExp()
 * @model
 * @generated
 */
public interface NotOpCallExp extends EObject
{
  /**
   * Returns the value of the '<em><b>Operation Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation Name</em>' attribute.
   * @see #setOperationName(String)
   * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getNotOpCallExp_OperationName()
   * @model
   * @generated
   */
  String getOperationName();

  /**
   * Sets the value of the '{@link fr.enseeiht.ocl.xtext.ocl.NotOpCallExp#getOperationName <em>Operation Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation Name</em>' attribute.
   * @see #getOperationName()
   * @generated
   */
  void setOperationName(String value);

  /**
   * Returns the value of the '<em><b>Source</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' containment reference.
   * @see #setSource(EObject)
   * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getNotOpCallExp_Source()
   * @model containment="true"
   * @generated
   */
  EObject getSource();

  /**
   * Sets the value of the '{@link fr.enseeiht.ocl.xtext.ocl.NotOpCallExp#getSource <em>Source</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' containment reference.
   * @see #getSource()
   * @generated
   */
  void setSource(EObject value);

} // NotOpCallExp
