/**
 * generated by Xtext
 */
package fr.enseeiht.ocl.xtext.ocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Numeric Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getNumericType()
 * @model
 * @generated
 */
public interface NumericType extends Primitive
{
} // NumericType
