/**
 * generated by Xtext 2.32.0
 */
package fr.enseeiht.ocl.xtext.ocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Undefined Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getOclUndefinedExp()
 * @model
 * @generated
 */
public interface OclUndefinedExp extends OclExpression
{
} // OclUndefinedExp
