/**
 * generated by Xtext
 */
package fr.enseeiht.ocl.xtext.ocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operator Call Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.ocl.xtext.ocl.OperatorCallExp#getArgumentGauche <em>Argument Gauche</em>}</li>
 *   <li>{@link fr.enseeiht.ocl.xtext.ocl.OperatorCallExp#getOperationName <em>Operation Name</em>}</li>
 *   <li>{@link fr.enseeiht.ocl.xtext.ocl.OperatorCallExp#getArgumentDroite <em>Argument Droite</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getOperatorCallExp()
 * @model
 * @generated
 */
public interface OperatorCallExp extends OclExpression
{
  /**
   * Returns the value of the '<em><b>Argument Gauche</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Argument Gauche</em>' containment reference.
   * @see #setArgumentGauche(EqOpCallExp)
   * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getOperatorCallExp_ArgumentGauche()
   * @model containment="true"
   * @generated
   */
  EqOpCallExp getArgumentGauche();

  /**
   * Sets the value of the '{@link fr.enseeiht.ocl.xtext.ocl.OperatorCallExp#getArgumentGauche <em>Argument Gauche</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Argument Gauche</em>' containment reference.
   * @see #getArgumentGauche()
   * @generated
   */
  void setArgumentGauche(EqOpCallExp value);

  /**
   * Returns the value of the '<em><b>Operation Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation Name</em>' attribute.
   * @see #setOperationName(String)
   * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getOperatorCallExp_OperationName()
   * @model
   * @generated
   */
  String getOperationName();

  /**
   * Sets the value of the '{@link fr.enseeiht.ocl.xtext.ocl.OperatorCallExp#getOperationName <em>Operation Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation Name</em>' attribute.
   * @see #getOperationName()
   * @generated
   */
  void setOperationName(String value);

  /**
   * Returns the value of the '<em><b>Argument Droite</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Argument Droite</em>' containment reference.
   * @see #setArgumentDroite(OperatorCallExp)
   * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getOperatorCallExp_ArgumentDroite()
   * @model containment="true"
   * @generated
   */
  OperatorCallExp getArgumentDroite();

  /**
   * Sets the value of the '{@link fr.enseeiht.ocl.xtext.ocl.OperatorCallExp#getArgumentDroite <em>Argument Droite</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Argument Droite</em>' containment reference.
   * @see #getArgumentDroite()
   * @generated
   */
  void setArgumentDroite(OperatorCallExp value);

} // OperatorCallExp
