/**
 * generated by Xtext
 */
package fr.enseeiht.ocl.xtext.ocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primitive</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getPrimitive()
 * @model
 * @generated
 */
public interface Primitive extends OclType
{
} // Primitive
