/**
 * generated by Xtext
 */
package fr.enseeiht.ocl.xtext.ocl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rel Op Call Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.ocl.xtext.ocl.RelOpCallExp#getArgs <em>Args</em>}</li>
 *   <li>{@link fr.enseeiht.ocl.xtext.ocl.RelOpCallExp#getOperationNames <em>Operation Names</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getRelOpCallExp()
 * @model
 * @generated
 */
public interface RelOpCallExp extends EObject
{
  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.ocl.xtext.ocl.AddOpCallExp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getRelOpCallExp_Args()
   * @model containment="true"
   * @generated
   */
  EList<AddOpCallExp> getArgs();

  /**
   * Returns the value of the '<em><b>Operation Names</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation Names</em>' attribute list.
   * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getRelOpCallExp_OperationNames()
   * @model unique="false"
   * @generated
   */
  EList<String> getOperationNames();

} // RelOpCallExp
