/**
 * generated by Xtext
 */
package fr.enseeiht.ocl.xtext.ocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Self Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.enseeiht.ocl.xtext.ocl.OclPackage#getSelfExp()
 * @model
 * @generated
 */
public interface SelfExp extends OclExpression
{
} // SelfExp
