/*
 * generated by Xtext 2.32.0
 */
package fr.enseeiht.xtext.tocl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ToclUiModule extends AbstractToclUiModule {

	public ToclUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
