/*
 * generated by Xtext 2.37.0
 */
package fr.enseeiht.ocl.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractOclValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(fr.enseeiht.ocl.xtext.ocl.OclPackage.eINSTANCE);
		return result;
	}
}
