/*
 * generated by Xtext 2.32.0
 */
package fr.enseeiht.xtext.tocl.ui.tests;

import com.google.inject.Injector;
import fr.enseeiht.xtext.tocl.ui.internal.ToclActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ToclUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ToclActivator.getInstance().getInjector("fr.enseeiht.xtext.tocl.Tocl");
	}

}
