/**
 * generated by Xtext 2.32.0
 */
package fr.enseeiht.xtext.tocl.tocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mul Op Call Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.enseeiht.xtext.tocl.tocl.ToclPackage#getMulOpCallExp()
 * @model
 * @generated
 */
public interface MulOpCallExp extends OperatorCallExp
{
} // MulOpCallExp
