/*
 * generated by Xtext
 */
package fr.enseeiht.ocl.xtext.serializer;

import com.google.inject.Inject;
import fr.enseeiht.ocl.xtext.services.OclGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class OclSyntacticSequencer extends AbstractSyntacticSequencer {

	protected OclGrammarAccess grammarAccess;
	protected AbstractElementAlias match_TupleType_TupleKeyword_1_1_or_TupleTypeKeyword_1_0;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (OclGrammarAccess) access;
		match_TupleType_TupleKeyword_1_1_or_TupleTypeKeyword_1_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getTupleTypeAccess().getTupleKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getTupleTypeAccess().getTupleTypeKeyword_1_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_TupleType_TupleKeyword_1_1_or_TupleTypeKeyword_1_0.equals(syntax))
				emit_TupleType_TupleKeyword_1_1_or_TupleTypeKeyword_1_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'TupleType' | 'Tuple'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '(' ')' (rule start)
	 *     (rule start) (ambiguity) '(' attributes+=TupleTypeAttribute
	 
	 * </pre>
	 */
	protected void emit_TupleType_TupleKeyword_1_1_or_TupleTypeKeyword_1_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
