/*
 * generated by Xtext 2.37.0
 */
package fr.enseeiht.ocl.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OclAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/enseeiht/ocl/xtext/parser/antlr/internal/InternalOcl.tokens");
	}
}
