/*
 * generated by Xtext 2.37.0
 */
package fr.enseeiht.ocl.xtext.parser.antlr;

import com.google.inject.Inject;
import fr.enseeiht.ocl.xtext.parser.antlr.internal.InternalOclParser;
import fr.enseeiht.ocl.xtext.services.OclGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class OclParser extends AbstractAntlrParser {

	@Inject
	private OclGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOclParser createParser(XtextTokenStream stream) {
		return new InternalOclParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Module";
	}

	public OclGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OclGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
