/**
 * generated by Xtext
 */
package fr.enseeiht.ocl.xtext.ocl.impl;

import fr.enseeiht.ocl.xtext.ocl.AddOpCallExp;
import fr.enseeiht.ocl.xtext.ocl.IntOpCallExp;
import fr.enseeiht.ocl.xtext.ocl.OclPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Add Op Call Exp</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.ocl.xtext.ocl.impl.AddOpCallExpImpl#getArgs <em>Args</em>}</li>
 *   <li>{@link fr.enseeiht.ocl.xtext.ocl.impl.AddOpCallExpImpl#getOperationNames <em>Operation Names</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AddOpCallExpImpl extends MinimalEObjectImpl.Container implements AddOpCallExp
{
  /**
   * The cached value of the '{@link #getArgs() <em>Args</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArgs()
   * @generated
   * @ordered
   */
  protected EList<IntOpCallExp> args;

  /**
   * The cached value of the '{@link #getOperationNames() <em>Operation Names</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperationNames()
   * @generated
   * @ordered
   */
  protected EList<String> operationNames;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AddOpCallExpImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OclPackage.Literals.ADD_OP_CALL_EXP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<IntOpCallExp> getArgs()
  {
    if (args == null)
    {
      args = new EObjectContainmentEList<IntOpCallExp>(IntOpCallExp.class, this, OclPackage.ADD_OP_CALL_EXP__ARGS);
    }
    return args;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getOperationNames()
  {
    if (operationNames == null)
    {
      operationNames = new EDataTypeEList<String>(String.class, this, OclPackage.ADD_OP_CALL_EXP__OPERATION_NAMES);
    }
    return operationNames;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OclPackage.ADD_OP_CALL_EXP__ARGS:
        return ((InternalEList<?>)getArgs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OclPackage.ADD_OP_CALL_EXP__ARGS:
        return getArgs();
      case OclPackage.ADD_OP_CALL_EXP__OPERATION_NAMES:
        return getOperationNames();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OclPackage.ADD_OP_CALL_EXP__ARGS:
        getArgs().clear();
        getArgs().addAll((Collection<? extends IntOpCallExp>)newValue);
        return;
      case OclPackage.ADD_OP_CALL_EXP__OPERATION_NAMES:
        getOperationNames().clear();
        getOperationNames().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OclPackage.ADD_OP_CALL_EXP__ARGS:
        getArgs().clear();
        return;
      case OclPackage.ADD_OP_CALL_EXP__OPERATION_NAMES:
        getOperationNames().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OclPackage.ADD_OP_CALL_EXP__ARGS:
        return args != null && !args.isEmpty();
      case OclPackage.ADD_OP_CALL_EXP__OPERATION_NAMES:
        return operationNames != null && !operationNames.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (operationNames: ");
    result.append(operationNames);
    result.append(')');
    return result.toString();
  }

} //AddOpCallExpImpl
