/**
 * generated by Xtext 2.32.0
 */
package fr.enseeiht.ocl.xtext.ocl.impl;

import fr.enseeiht.ocl.xtext.ocl.MulOpCallExp;
import fr.enseeiht.ocl.xtext.ocl.OclPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Mul Op Call Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MulOpCallExpImpl extends OperatorCallExpImpl implements MulOpCallExp
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MulOpCallExpImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OclPackage.Literals.MUL_OP_CALL_EXP;
  }

} //MulOpCallExpImpl
