/*
 * generated by Xtext
 */
package fr.enseeiht.ocl.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOclScopeProvider extends DelegatingScopeProvider {
}
