/*
 * generated by Xtext 2.32.0
 */
package fr.enseeiht.ocl.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOclScopeProvider extends DelegatingScopeProvider {
}
