/**
 * generated by Xtext 2.32.0
 */
package fr.enseeiht.xtext.tocl.tocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.xtext.tocl.tocl.VariableExp#getReferredVariable <em>Referred Variable</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.xtext.tocl.tocl.ToclPackage#getVariableExp()
 * @model
 * @generated
 */
public interface VariableExp extends OclExpression
{
  /**
   * Returns the value of the '<em><b>Referred Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Referred Variable</em>' reference.
   * @see #setReferredVariable(Auxiliary)
   * @see fr.enseeiht.xtext.tocl.tocl.ToclPackage#getVariableExp_ReferredVariable()
   * @model
   * @generated
   */
  Auxiliary getReferredVariable();

  /**
   * Sets the value of the '{@link fr.enseeiht.xtext.tocl.tocl.VariableExp#getReferredVariable <em>Referred Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Referred Variable</em>' reference.
   * @see #getReferredVariable()
   * @generated
   */
  void setReferredVariable(Auxiliary value);

} // VariableExp
