/*
 * generated by Xtext 2.32.0
 */
package fr.enseeiht.xtext.tocl.parser.antlr;

import com.google.inject.Inject;
import fr.enseeiht.xtext.tocl.parser.antlr.internal.InternalToclParser;
import fr.enseeiht.xtext.tocl.services.ToclGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ToclParser extends AbstractAntlrParser {

	@Inject
	private ToclGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalToclParser createParser(XtextTokenStream stream) {
		return new InternalToclParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Module";
	}

	public ToclGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ToclGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
