/**
 * generated by Xtext 2.32.0
 */
package fr.enseeiht.xtext.tocl.tocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integer Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.enseeiht.xtext.tocl.tocl.ToclPackage#getIntegerType()
 * @model
 * @generated
 */
public interface IntegerType extends NumericType
{
} // IntegerType
