/**
 * generated by Xtext 2.32.0
 */
package fr.enseeiht.xtext.tocl.tocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Numeric Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.enseeiht.xtext.tocl.tocl.ToclPackage#getNumericExp()
 * @model
 * @generated
 */
public interface NumericExp extends OclExpression
{
} // NumericExp
