/**
 * generated by Xtext 2.32.0
 */
package fr.enseeiht.xtext.tocl.tocl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.xtext.tocl.tocl.OperationCall#getOperationName <em>Operation Name</em>}</li>
 *   <li>{@link fr.enseeiht.xtext.tocl.tocl.OperationCall#getArguments <em>Arguments</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.xtext.tocl.tocl.ToclPackage#getOperationCall()
 * @model
 * @generated
 */
public interface OperationCall extends PropertyCall
{
  /**
   * Returns the value of the '<em><b>Operation Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation Name</em>' attribute.
   * @see #setOperationName(String)
   * @see fr.enseeiht.xtext.tocl.tocl.ToclPackage#getOperationCall_OperationName()
   * @model
   * @generated
   */
  String getOperationName();

  /**
   * Sets the value of the '{@link fr.enseeiht.xtext.tocl.tocl.OperationCall#getOperationName <em>Operation Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation Name</em>' attribute.
   * @see #getOperationName()
   * @generated
   */
  void setOperationName(String value);

  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.xtext.tocl.tocl.OclExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference list.
   * @see fr.enseeiht.xtext.tocl.tocl.ToclPackage#getOperationCall_Arguments()
   * @model containment="true"
   * @generated
   */
  EList<OclExpression> getArguments();

} // OperationCall
