/**
 * generated by Xtext 2.32.0
 */
package fr.enseeiht.xtext.tocl.tocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ordered Set Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.enseeiht.xtext.tocl.tocl.ToclPackage#getOrderedSetType()
 * @model
 * @generated
 */
public interface OrderedSetType extends CollectionType
{
} // OrderedSetType
