/**
 * generated by Xtext 2.32.0
 */
package fr.enseeiht.xtext.tocl.tocl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tuple Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.xtext.tocl.tocl.TupleType#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.xtext.tocl.tocl.ToclPackage#getTupleType()
 * @model
 * @generated
 */
public interface TupleType extends OclType
{
  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.xtext.tocl.tocl.TupleTypeAttribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see fr.enseeiht.xtext.tocl.tocl.ToclPackage#getTupleType_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<TupleTypeAttribute> getAttributes();

} // TupleType
