/*
 * generated by Xtext 2.37.0
 */
package fr.enseeiht.ocl.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class OclUiModule extends AbstractOclUiModule {

	public OclUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
